// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwp_ZBtQ_10q5VFL77Larl704cHeNOSNM',
    appId: '1:414030755976:web:29565eb8d73ab6b2db473d',
    messagingSenderId: '414030755976',
    projectId: 'bedavanevar-2019',
    authDomain: 'bedavanevar-2019.firebaseapp.com',
    databaseURL: 'https://bedavanevar-2019.firebaseio.com',
    storageBucket: 'bedavanevar-2019.appspot.com',
    measurementId: 'G-EX20Z8DEQZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDel_nqQHo3EGU1Z6ImVl-pWtPzvzFgAmI',
    appId: '1:414030755976:android:de6bf27a05e95647db473d',
    messagingSenderId: '414030755976',
    projectId: 'bedavanevar-2019',
    databaseURL: 'https://bedavanevar-2019.firebaseio.com',
    storageBucket: 'bedavanevar-2019.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCek-GYYKmxEk6gsKm09UnBfIjxcoZkpOA',
    appId: '1:414030755976:ios:20db31bffb5bf8f5db473d',
    messagingSenderId: '414030755976',
    projectId: 'bedavanevar-2019',
    databaseURL: 'https://bedavanevar-2019.firebaseio.com',
    storageBucket: 'bedavanevar-2019.appspot.com',
    androidClientId: '414030755976-orngna1ba8t168vbacq3khr9ov6trasr.apps.googleusercontent.com',
    iosClientId: '414030755976-333ecgfufbcjqijb5k3bnsqclas5t0i0.apps.googleusercontent.com',
    iosBundleId: 'com.kaloglu.BedavaNeVar',
  );
}
